apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uexpress-sitemap-job
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uexpress-sitemap
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: dearabby-letters-config 
              - secretRef:
                  name: dearabby-letters-config-secret 
            resources: {}
            imagePullPolicy: Always
            args:
            - rake
            - -s sitemap:refresh
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
          securityContext: {}
          imagePullSecrets:
            - name: image-pull-secret
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
